### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ErssonAE**
Changed 2020 Corner Connector Amount from 8 to 10

### CODE REVIEW

**Comment by Cairo555** [comment]
I agree, just started printing two more.
It's not hard to build, but the instructions could be a bit more clear. In my fork i'm trying to work on that.

**Review by Cairo555 — APPROVED** [review]
Agree, need two more for the part where risers connect.

**Comment by androdz1** [comment]
how did you print the 2020 and 90 files?  it wont let me download it

**Comment by Cairo555** [comment]
> how did you print the 2020 and 90 files? it wont let me download it

It's better to start a new issue. Can you download the other files? You can download the whole thing in one zip file.
Do you get an error message?

**Pull request closed without merging**
